# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jacob Jones
tagline:          'The portfolio of Jacob Jones'
description:      'A full-stack software engineer hailing from Spokane, Washington.'
url:              jacobjones.io
baseurl:          /

author:
  name:           'Jacob Jones'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/truejacobjones/truejacobjones.github.io
