# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jacob Jones
tagline:          'Portfolio'
description:      'A full-stack software engineer from Spokane, Washington.'
url:              jacobjones.io
baseurl:          /

author:
  name:           'Jacob Jones'

paginate:         5
